### ISSUE TITLE
Error in lower.to.upper.tri.inds(n) : 'n' must be >= 2

### ISSUE THREAD

**Issue by trwo** [steverozen/mSigHdp#2]
Hello. I am running mSigHdp for the first time. I successfully ran the vignette and I am now attempting to run it for my data (~100 samples, 400-500 subs each, very similar mutational spectra across the cohort). 

Running RunHdpxParallel using the parameter settings from the vignette (to check that it runs successfully before adjusting the parameters to increase the burnins etc.), I get the following error: "Error in lower.to.upper.tri.inds(n) : 'n' must be >= 2" once it attempts to call extract_components.

Do you know why this error might arise for my real life data but not the toy data? Would changing any of the parameters avoid this?

Thanks for your time and for creating this tool!

**Comment by jnh01** [comment]
@trwo 
Hello, thanks for providing details about the issue you faced using mSigHdp.

We managed to reproduce the same error you encountered using some test data. As you have very similar mutational spectra in your cohort, so the algorithm can find **_only one_** cluster to be later converted to final signature. In this edge case, the code will break. While in the toy data, some spectra are very different from others.

 We have updated our code to accommodate for this. You should not need to change any of the parameters. Can you try installing latest hdpx and mSigHdp from GitHub, restart R and test whether your issue is solved?

`remotes::install_github(repo = "steverozen/hdpx", ref = "v1.0.2-branch")`
`remotes::install_github(repo = "steverozen/mSigHdp", ref = "v2.0.2-branch")`
`.rs.restartR()`

**Comment by trwo** [comment]
@jnh01 Thanks for getting back to me. I can confirm that my issue has been resolved by this update. Cheers!

**Comment by jnh01** [comment]
@trwo Great, thank you!
